name: vehicle_registration_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_smart_dialog: ^4.5.5+3
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  image_picker: ^0.8.5+3
  url_strategy: ^0.2.0
  auto_route: ^5.0.1
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.2
  build_runner:  
  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
   


